/*
 * ImageManipulationWizard.java
 *
 * Created on 11. September 2002, 21:12
 */

package org.wewi.medimg.image.wizard;

import org.wewi.medimg.viewer.wizard.Wizard;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
public class ImageManipulationWizard extends Wizard {
    
    /** Creates new form ImageManipulationWizard */
    public ImageManipulationWizard() {
        initComponents();
    }
    
    public String getMenuName() {
        return null;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        filterPanel = new javax.swing.JPanel();
        filterComboBox = new javax.swing.JComboBox();
        filterPanelCenter = new javax.swing.JPanel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Bildmanipulator");
        filterPanel.setLayout(new java.awt.BorderLayout());

        filterPanel.add(filterComboBox, java.awt.BorderLayout.NORTH);

        filterPanel.add(filterPanelCenter, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Filter", null, filterPanel, "null");

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(568, 425));
        setLocation((screenSize.width-568)/2,(screenSize.height-425)/2);
    }//GEN-END:initComponents

       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox filterComboBox;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel filterPanelCenter;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    

}
