/**
 * MAPKMeansClustererArgumentPanel.java
 *
 * Created on 11. August 2002, 21:16
 */

package org.wewi.medimg.viewer.wizard.seg;

import java.text.NumberFormat;

import org.wewi.medimg.seg.ObservableSegmenter;
import org.wewi.medimg.seg.stat.MAPKMeansClusterer;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1 
 */
public final class MAPKMeansClustererArgumentPanel extends SegmenterArgumentPanel {
    private int nfeatures = 1;
    
    private final static double BETA_DIVISOR = 1000d;
    private int beta = 30;
    
    private NumberFormat format;
    
    
    /** Creates new form MAPKMeansClustererArgumentPanel */
    public MAPKMeansClustererArgumentPanel() {
        initComponents();
        init();
    }
    
    private void init() {
        format = NumberFormat.getInstance();
        format.setMaximumFractionDigits(3);
        format.setMinimumFractionDigits(3);
        format.setMaximumIntegerDigits(4);
        format.setMinimumIntegerDigits(1);        
          
        nfeatures = nfeaturesSlider.getValue();
        beta = betaSlider.getValue();  
        
        betaLabel.setText("  Beta (Gibbspotential):    " + format.format((double)beta/BETA_DIVISOR));         
    }
    
    public ObservableSegmenter getSegmenter() {
        MAPKMeansClusterer clusterer = new MAPKMeansClusterer(nfeatures);
        clusterer.setBETA((double)beta/BETA_DIVISOR);
        return clusterer;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        propertyLabel = new javax.swing.JLabel();
        nfeaturesSlider = new javax.swing.JSlider();
        betaLabel = new javax.swing.JLabel();
        betaSlider = new javax.swing.JSlider();

        setLayout(new java.awt.GridLayout(2, 2));

        setBorder(new javax.swing.border.TitledBorder(null, "MAP-Segmentierer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12)));
        propertyLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        propertyLabel.setText("  Anzahl der Merkmale:    2");
        propertyLabel.setAlignmentX(0.5F);
        add(propertyLabel);

        nfeaturesSlider.setMajorTickSpacing(5);
        nfeaturesSlider.setMaximum(20);
        nfeaturesSlider.setMinimum(2);
        nfeaturesSlider.setMinorTickSpacing(1);
        nfeaturesSlider.setPaintTicks(true);
        nfeaturesSlider.setSnapToTicks(true);
        nfeaturesSlider.setValue(2);
        nfeaturesSlider.setDoubleBuffered(true);
        nfeaturesSlider.setValueIsAdjusting(true);
        nfeaturesSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nfeaturesSliderStateChanged(evt);
            }
        });

        add(nfeaturesSlider);

        betaLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        betaLabel.setText("  Beta (Gibbspotential):    0,30");
        add(betaLabel);

        betaSlider.setMajorTickSpacing(100);
        betaSlider.setMaximum(1200);
        betaSlider.setMinorTickSpacing(50);
        betaSlider.setPaintTicks(true);
        betaSlider.setValue(300);
        betaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                betaSliderStateChanged(evt);
            }
        });

        add(betaSlider);

    }//GEN-END:initComponents

    private void betaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_betaSliderStateChanged
        beta = betaSlider.getValue();
        betaLabel.setText("  Beta (Gibbspotential):    " + format.format((double)beta/BETA_DIVISOR));
    }//GEN-LAST:event_betaSliderStateChanged

    private void nfeaturesSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nfeaturesSliderStateChanged
        nfeatures = nfeaturesSlider.getValue();
        propertyLabel.setText("  Anzahl der Merkmale:    " + nfeatures);
    }//GEN-LAST:event_nfeaturesSliderStateChanged
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel propertyLabel;
    private javax.swing.JLabel betaLabel;
    private javax.swing.JSlider betaSlider;
    private javax.swing.JSlider nfeaturesSlider;
    // End of variables declaration//GEN-END:variables
    
}
