/**
 * MLKMeansClustererArgumentPanel.java
 *
 * Created on 11. August 2002, 21:16
 */

package org.wewi.medimg.viewer.wizard.seg;

import org.wewi.medimg.seg.ObservableSegmenter;
import org.wewi.medimg.seg.stat.MLKMeansClusterer;

/**
 *
 * @author  Franz Wilhelmstötter 
 * @version 0.1
 */
public class MLKMeansClustererArgumentPanel extends SegmenterArgumentPanel { 
    private int nfeatures = 2;
    
    /** Creates new form MLKMeansClustererArgumentPanel */
    public MLKMeansClustererArgumentPanel() { 
        initComponents();
    }
    
    public ObservableSegmenter getSegmenter() {
        return new MLKMeansClusterer(nfeatures); 
    }     
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        propertyLabel = new javax.swing.JLabel();
        nfeatureSlide = new javax.swing.JSlider();

        setLayout(new java.awt.GridLayout(1, 0));

        setBorder(new javax.swing.border.TitledBorder(null, "ML-Segmentierer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12)));
        propertyLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        propertyLabel.setText("  Anzahl der Merkmale:    2");
        add(propertyLabel);

        nfeatureSlide.setMajorTickSpacing(5);
        nfeatureSlide.setMaximum(20);
        nfeatureSlide.setMinimum(2);
        nfeatureSlide.setMinorTickSpacing(1);
        nfeatureSlide.setPaintTicks(true);
        nfeatureSlide.setSnapToTicks(true);
        nfeatureSlide.setValue(2);
        nfeatureSlide.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nfeatureSlideStateChanged(evt);
            }
        });

        add(nfeatureSlide);

    }//GEN-END:initComponents

    private void nfeatureSlideStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nfeatureSlideStateChanged
        nfeatures = nfeatureSlide.getValue();
        propertyLabel.setText("  Anzahl der Merkmale:    " + nfeatures);
    }//GEN-LAST:event_nfeatureSlideStateChanged
               
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel propertyLabel;
    private javax.swing.JSlider nfeatureSlide;
    // End of variables declaration//GEN-END:variables
        
}
