/*
 * SegmentationWizard.java
 *
 * Created on 7. April 2002, 12:12
 */

package org.wewi.medimg.visualisation.mc.wizard;

import java.beans.PropertyVetoException;
import java.io.File;

import javax.swing.JFileChooser;

import org.wewi.medimg.image.IntImageFactory;
import org.wewi.medimg.image.io.ImageReader;
import org.wewi.medimg.image.io.ImageReaderFactory;
import org.wewi.medimg.viewer.ImageFileChooser;
import org.wewi.medimg.viewer.Viewer;
import org.wewi.medimg.viewer.wizard.Wizard;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
public class MarchingCubeWizard extends Wizard {             
    private static final String MENU_NAME = "Marching Cube";
    
    private ImageReader imageReader = null;
    private int greyValueFrom = 0;
    private int greyValueTo = 0;
    private int gridSize = 1;
    
    /** Creates new form SegmentationWizard */
    public MarchingCubeWizard() {
        super(MENU_NAME, false, true, false, false);
        initComponents();
        init();
    }    
    
    public String getMenuName() {
        return MENU_NAME;
    }
    
    private void init() {
        //triangleDecimationComboBox.addItem(
    }
    
    private void onClose() {
        try {
            //imageViewer.setClosed(true);
            setClosed(true);
            //dispose();
            Viewer.getInstance().removeWizard(this);
        } catch (PropertyVetoException pve) {
            //Zur Zeit nichts
        }        
    }    
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        northPanel = new javax.swing.JPanel();
        southPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        marchingCubePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imageFileNameTextField = new javax.swing.JTextField();
        chooseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        greyValueFromTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        greyValueToTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gridSizeTextField = new javax.swing.JTextField();
        triangleDecimationPanel = new javax.swing.JPanel();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        addAllButton = new javax.swing.JButton();
        removeAllButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jList2 = new javax.swing.JList();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        cancelButton.setText("Abbrechen");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        southPanel.add(cancelButton);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        southPanel.add(startButton);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(eastPanel, java.awt.BorderLayout.EAST);

        getContentPane().add(westPanel, java.awt.BorderLayout.WEST);

        centerPanel.setLayout(new java.awt.GridLayout());

        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(471, 150));
        marchingCubePanel.setLayout(new java.awt.GridLayout(2, 1));

        imageFileNameTextField.setEditable(false);
        imageFileNameTextField.setPreferredSize(new java.awt.Dimension(300, 20));
        imageFileNameTextField.setEnabled(false);
        jPanel1.add(imageFileNameTextField);

        chooseButton.setText("Datensatz w\u00e4hlen");
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        jPanel1.add(chooseButton);

        marchingCubePanel.add(jPanel1);

        jLabel1.setText("Schwellwert:");
        jPanel2.add(jLabel1);

        greyValueFromTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        greyValueFromTextField.setText("0");
        greyValueFromTextField.setMinimumSize(new java.awt.Dimension(50, 20));
        greyValueFromTextField.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(greyValueFromTextField);

        jLabel2.setText("-");
        jPanel2.add(jLabel2);

        greyValueToTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        greyValueToTextField.setText("0");
        greyValueToTextField.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(greyValueToTextField);

        jLabel4.setText("    Raster:");
        jPanel2.add(jLabel4);

        gridSizeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridSizeTextField.setText("1");
        gridSizeTextField.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(gridSizeTextField);

        marchingCubePanel.add(jPanel2);

        jTabbedPane1.addTab("Marching Cube", marchingCubePanel);

        triangleDecimationPanel.setLayout(new java.awt.GridLayout(1, 3));

        jList1.setBorder(new javax.swing.border.TitledBorder("Ausgew\u00e4hlte Methoden"));
        triangleDecimationPanel.add(jList1);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        addAllButton.setText("<<");
        addAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllButtonActionPerformed(evt);
            }
        });

        jPanel3.add(addAllButton);

        removeAllButton.setText(">>");
        removeAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllButtonActionPerformed(evt);
            }
        });

        jPanel3.add(removeAllButton);

        addButton.setText("<");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jPanel3.add(addButton);

        removeButton.setText(">");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jPanel3.add(removeButton);

        triangleDecimationPanel.add(jPanel3);

        jList2.setBorder(new javax.swing.border.TitledBorder("M\u00f6gliche Methoden"));
        triangleDecimationPanel.add(jList2);

        jTabbedPane1.addTab("Dreiecksreduktion", triangleDecimationPanel);

        centerPanel.add(jTabbedPane1);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_removeAllButtonActionPerformed

    private void addAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_addAllButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        // Add your handling code here:
        ImageFileChooser chooser = new ImageFileChooser();
        chooser.setDialogTitle("Datensatz auswählen");
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setCurrentDirectory(new File("C:/Workspace/fwilhelm/Projekte/Diplom/data"));
        
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal != JFileChooser.APPROVE_OPTION) {
            return;
        }
        
        ImageReaderFactory readerFactory = chooser.getImageReaderFactory();
        String fileName = chooser.getSelectedFile().getAbsolutePath();
        imageReader = readerFactory.createImageReader(IntImageFactory.getInstance(),
                                                                  new File(fileName));        
        imageFileNameTextField.setText(fileName);        
    }//GEN-LAST:event_chooseButtonActionPerformed

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_startButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // Add your handling code here:
        onClose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // Add your handling code here:
        try {
            setClosed(true);
            Viewer.getInstance().removeWizard(this);
        } catch (PropertyVetoException pve) {
            //Zur Zeit nichts
        } 
    }//GEN-LAST:event_formInternalFrameClosed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel southPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton chooseButton;
    private javax.swing.JTextField gridSizeTextField;
    private javax.swing.JTextField greyValueToTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel westPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton addAllButton;
    private javax.swing.JTextField greyValueFromTextField;
    private javax.swing.JPanel marchingCubePanel;
    private javax.swing.JButton removeAllButton;
    private javax.swing.JPanel triangleDecimationPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField imageFileNameTextField;
    private javax.swing.JList jList2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel eastPanel;
    // End of variables declaration//GEN-END:variables
    
}
