/*
 * SegmentationWizard.java
 *
 * Created on 7. April 2002, 12:12
 */

package org.wewi.medimg.visualisation.mc.wizard;

import org.wewi.medimg.util.Singleton;

import org.wewi.medimg.image.Image;
import org.wewi.medimg.image.NullImage;
import org.wewi.medimg.image.ImageData;
import org.wewi.medimg.image.ImageDataFactory;
import org.wewi.medimg.image.ImageFormatTypes;
import org.wewi.medimg.image.FeatureColorConversion;

import org.wewi.medimg.image.io.ImageReader;
import org.wewi.medimg.image.io.ImageReaderThread;
import org.wewi.medimg.image.io.ImageReaderFactory;
import org.wewi.medimg.image.io.TIFFReaderFactory;
import org.wewi.medimg.image.io.BMPReaderFactory;
import org.wewi.medimg.image.io.RawImageReaderFactory;
import org.wewi.medimg.image.io.RawImageDataReaderFactory;
import org.wewi.medimg.image.io.ReaderThreadListener;
import org.wewi.medimg.image.io.WriterThreadListener;
import org.wewi.medimg.image.io.ReaderThreadEvent;
import org.wewi.medimg.image.io.WriterThreadEvent;
import org.wewi.medimg.image.io.Range;

import org.wewi.medimg.seg.FeatureImage;
import org.wewi.medimg.seg.SegmentationStrategy;
import org.wewi.medimg.seg.SegmentationEvent;
import org.wewi.medimg.seg.SegmentationKind;
import org.wewi.medimg.seg.ImageSegmentationStrategy;
import org.wewi.medimg.seg.SegmentationStrategyThread;
import org.wewi.medimg.seg.SegmentationListener;
import org.wewi.medimg.seg.statistic.MLSegmentation;
import org.wewi.medimg.seg.statistic.MAPSegmentation;

import org.wewi.medimg.viewer.wizard.Wizard;
import org.wewi.medimg.viewer.Viewer;
import org.wewi.medimg.viewer.ImageFileChooser;

import java.util.Observer;
import java.util.Observable;

import java.io.File;

import java.beans.PropertyVetoException;

import javax.swing.JInternalFrame;
import javax.swing.JFileChooser;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
public class MarchingCubeWizard extends Wizard implements Observer, ReaderThreadListener, WriterThreadListener, SegmentationListener {
                                                              
    private static final String MENU_NAME = "Marching Cube-Wizard";
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // Add your handling code here:
        try {
            setClosed(true);
            Viewer.getInstance().removeWizard(this);
        } catch (PropertyVetoException pve) {
            //Zur Zeit nichts
        } 
    }//GEN-LAST:event_formInternalFrameClosed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
