/*
 * MAPKMeansClustererArgumentPanel.java
 *
 * Created on 11. August 2002, 21:16
 */

package org.wewi.medimg.seg.wizard;

/**
 *
 * @author  Franz Wilhelmstötter
 */
public class MAPKMeansClustererArgumentPanel extends javax.swing.JPanel {
    
    /** Creates new form MAPKMeansClustererArgumentPanel */
    public MAPKMeansClustererArgumentPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
