/*
 * AboutFrame.java
 *
 * Created on 02. April 2002, 22:51
 */

package org.wewi.medimg.viewer;

/**
 *
 * @author  fwilhelm
 */
public class AboutFrame extends javax.swing.JInternalFrame {

    /** Creates new form AboutFrame */
    public AboutFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setTitle("About");
        setClosable(true);
        try {
            setIcon(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/org/wewi/medimg/viewer/icons/logo.gif")));
        setVisible(true);
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(300, 200));
        setLocation((screenSize.width-300)/2,(screenSize.height-200)/2);
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
