/**
 * CCChooserPanel.java
 *
 * Created on 4. Oktober 2002, 20:20
 */

package org.wewi.medimg.viewer;

import org.wewi.medimg.image.ColorConversion;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
public class CCChooserPanel extends javax.swing.JPanel {
    private ColorConversion colorConversion;
    
    /** Creates new form CCChooserPanel */
    public CCChooserPanel() {
        initComponents();
        init();
    }
    
    public void init() {
        
    }
    
    public ColorConversion getColorConversion() {
        return colorConversion;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ccComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        ccComboBox.setFont(new java.awt.Font("Dialog", 0, 12));
        ccComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccComboBoxActionPerformed(evt);
            }
        });

        add(ccComboBox, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void ccComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccComboBoxActionPerformed

    }//GEN-LAST:event_ccComboBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ccComboBox;
    // End of variables declaration//GEN-END:variables
    
}
