/*
 * LogHandlerPanel.java
 *
 * Created on 21. August 2002, 15:29
 */

package org.wewi.medimg.viewer;

/**
 *
 * @author  Franz Wilhelmstötter
 */
public class LogHandlerPanel extends javax.swing.JPanel {
    
    /** Creates new form LogHandlerPanel */
    public LogHandlerPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        logTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        add(logTextArea, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea logTextArea;
    // End of variables declaration//GEN-END:variables
    
}
