/*
 * ProgressFrame.java
 *
 * Created on 22. August 2002, 17:42
 */

package org.wewi.medimg.viewer;

import java.awt.Point;


/**
 *
* @author  Franz Wilhelmstötter
 */
public class ProgressFrame extends ViewerDesktopFrame {
    
    /** Creates new form ProgressFrame */
    public ProgressFrame() { 
        initComponents();
        init();
    }
    
    private void init() {
        Viewer v = Viewer.getInstance();
        Point p = new Point(v.getWidth()/2 - getWidth()/2, 
                            v.getHeight()/2 - getHeight()/2 - 50);  
        setLocation(p);  
    }
    
    public void setProgress(double progress) {
        progressBar.setValue((int)(progress*100));
    }
    
    public void setSubTitle(String subTitle) {
        subTitleLabel.setText(subTitle);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        subTitleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();

        setIconifiable(true);
        setResizable(true);
        subTitleLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        jPanel1.add(subTitleLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        progressBar.setFont(new java.awt.Font("Dialog", 0, 12));
        progressBar.setStringPainted(true);
        jPanel2.add(progressBar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(451, 94));
        setLocation((screenSize.width-451)/2,(screenSize.height-94)/2);
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel subTitleLabel;
    // End of variables declaration//GEN-END:variables
    
}
