/*
 * RangePanel.java
 *
 * Created on 17. Juni 2002, 19:15
 */

package org.wewi.medimg.viewer;

import org.wewi.medimg.image.io.Range;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
class RangePanel extends javax.swing.JPanel {
    private int min = 0;
    private int max = 1000;
    private int stride = 1;
    
    /** Creates new form RangePanel */
    public RangePanel() {
        initComponents();
    }
    
    public Range getRange() {
        return new Range(min, max, stride);
    }
    
    public void setRange(Range range) {
        min = range.getMinSlice();
        max = range.getMaxSlice();
        stride = range.getStride();
    }
    
    private boolean testMinSlice(String s) {
        try {
            int minTemp = Integer.parseInt(s);
            if (minTemp <= max) {
                min = minTemp;
                return true;
            } else {
                return false;
            }
        } catch (NumberFormatException nfe) {
            return false;
        }
    }
    
    private boolean testMaxSlice(String s) {
        try {
            int maxTemp = Integer.parseInt(s);
            if (maxTemp >= min) {
                max = maxTemp;
                return true;
            } else {
                return false;
            }            
        } catch (NumberFormatException nfe) {
            return false;
        }
    }    
    
    
    private boolean testStride(String s) {
        try {
            int strideTemp = Integer.parseInt(s);
            if (strideTemp <= (max-min)) {
                stride = strideTemp;
                return true;
            } else {
                return false;
            }            
        } catch (NumberFormatException nfe) {
            return false;
        }
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        rangeFromLabel = new javax.swing.JLabel();
        rangeFromTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rangeToLabel = new javax.swing.JLabel();
        rangeToTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        strideLabel = new javax.swing.JLabel();
        strideTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(4, 1));

        setBorder(new javax.swing.border.TitledBorder("Bildbereich"));
        rangeFromLabel.setText("Schicht von");
        jPanel1.add(rangeFromLabel);

        rangeFromTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rangeFromTextField.setText("0");
        rangeFromTextField.setPreferredSize(new java.awt.Dimension(40, 20));
        rangeFromTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rangeFromTextFieldFocusLost(evt);
            }
        });

        jPanel1.add(rangeFromTextField);

        add(jPanel1);

        rangeToLabel.setText("Schicht bis");
        jPanel2.add(rangeToLabel);

        rangeToTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rangeToTextField.setText("1000");
        rangeToTextField.setPreferredSize(new java.awt.Dimension(40, 20));
        rangeToTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rangeToTextFieldFocusLost(evt);
            }
        });

        jPanel2.add(rangeToTextField);

        add(jPanel2);

        strideLabel.setText("Stride");
        jPanel3.add(strideLabel);

        strideTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        strideTextField.setText("1");
        strideTextField.setToolTipText("null");
        strideTextField.setMinimumSize(new java.awt.Dimension(5, 20));
        strideTextField.setName("null");
        strideTextField.setPreferredSize(new java.awt.Dimension(70, 20));
        strideTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                strideTextFieldFocusLost(evt);
            }
        });

        jPanel3.add(strideTextField);

        add(jPanel3);

        add(jPanel4);

    }//GEN-END:initComponents

    private void strideTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_strideTextFieldFocusLost
        // Add your handling code here:
        if (!testStride(strideTextField.getText())) {
            strideTextField.setText("" + stride);
        }
    }//GEN-LAST:event_strideTextFieldFocusLost

    private void rangeToTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rangeToTextFieldFocusLost
        // Add your handling code here:
        if (!testMaxSlice(rangeToTextField.getText())) {
            rangeToTextField.setText("" + max);
        }
    }//GEN-LAST:event_rangeToTextFieldFocusLost

    private void rangeFromTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rangeFromTextFieldFocusLost
        // Add your handling code here:
        if (!testMinSlice(rangeFromTextField.getText())) {
            rangeToTextField.setText("" + min);
        }        
    }//GEN-LAST:event_rangeFromTextFieldFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rangeToLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField strideTextField;
    private javax.swing.JLabel rangeFromLabel;
    private javax.swing.JLabel strideLabel;
    private javax.swing.JTextField rangeToTextField;
    private javax.swing.JTextField rangeFromTextField;
    // End of variables declaration//GEN-END:variables
    
}
