/**
 * ErrorListPlot.java
 *
 * Created on 14. Oktober 2002, 16:14
 */

package org.wewi.medimg.seg.validation;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
public class ErrorListPlot extends javax.swing.JFrame {
    private double[] mean;
    private double[] var;
    
    
    public ErrorListPlot() {
        initComponents();
        init();
    }
    
    /** Creates new form ErrorListPlot */
    public ErrorListPlot(double[] mean, double[] var) {
        this.mean = mean;
        this.var = var;
        initComponents();
        init();
    }
    
    public void init() { 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(400, 300));
        setLocation((screenSize.width-400)/2,(screenSize.height-300)/2);
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ErrorListPlot().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
