/**
 * CCChooserPanel.java
 *
 * Created on 4. Oktober 2002, 20:20
 */

package org.wewi.medimg.viewer.tools;

import org.wewi.medimg.image.ColorConversion;
import org.wewi.medimg.image.VoxelSelectorEvent;
import org.wewi.medimg.image.VoxelSelectorListener;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
public class CCChooserPanel extends javax.swing.JPanel implements VoxelSelectorListener {
    private ColorConversion colorConversion;
    
    /** Creates new form CCChooserPanel */
    public CCChooserPanel(ColorConversion colorConversion) {
        this.colorConversion = colorConversion;
        initComponents();
        init();
    }
    
    public void init() {
    }
    
    public ColorConversion getColorConversion() {
        return colorConversion;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tabelToolBar = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        
        setLayout(new java.awt.BorderLayout());
        
        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        jPanel1.setLayout(new java.awt.BorderLayout());
        
        jPanel1.setBorder(new javax.swing.border.TitledBorder(null, "ColorConversion-Editor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            
        },
        new String [] {
            
        }
        ));
        jScrollPane1.setViewportView(jTable1);
        
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        add(jPanel1, java.awt.BorderLayout.CENTER);
        
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        
        jPanel2.add(tabelToolBar);
        
        add(jPanel2, java.awt.BorderLayout.NORTH);
        
        add(jPanel3, java.awt.BorderLayout.SOUTH);
        
        add(jPanel4, java.awt.BorderLayout.EAST);
        
        add(jPanel5, java.awt.BorderLayout.WEST);
        
    }//GEN-END:initComponents

    public void voxelSelected(VoxelSelectorEvent event) {
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar tabelToolBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
