/* 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.    See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/**
 * ImagePropertiesDialog.java
 *
 * Created on 17. Februar 2003, 14:19
 */

package org.wewi.medimg.viewer.tools;

import org.wewi.medimg.image.ImageProperties;

/**
 *
 * @author  Franz Wilhelmstötter
 * @version 0.1
 */
public class ImagePropertiesDialog extends javax.swing.JDialog {
    private ImageProperties properties;
    
    /** Creates new form ImagePropertiesDialog */
    public ImagePropertiesDialog(ImageProperties properties, java.awt.Frame parent, boolean modal) {
        super(parent, "Image-Poperties", modal);
        this.properties = properties;
        initComponents();
        init();
    }
    
    private void init() { 
        getContentPane().add(new ImagePropertiesPanel(properties));
    }
    
    public ImageProperties getImageProperties() {
        return properties;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */ 
    private void initComponents() {//GEN-BEGIN:initComponents
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(379, 188));
        setLocation((screenSize.width-379)/2,(screenSize.height-188)/2);
    }//GEN-END:initComponents
    
    /** Closes the dialog */ 
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ImageProperties ip = new ImageProperties();
        ip.setProperty("Key1", "Value1");
        ip.setProperty("Key2", "Value2");
        ip.setProperty("Key3", "Value3");
        new ImagePropertiesDialog(ip, new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
