/*
 * TableToolPanel.java
 *
 * Created on 22. Februar 2003, 13:04
 */

package org.wewi.medimg.viewer.tools;

/**
 *
 * @author  fwilhelm
 */
public class TableToolPanel extends javax.swing.JPanel {
    
    /** Creates new form TableToolPanel */
    public TableToolPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
